### ISSUE TITLE
Convert single column layout to sidebar

### ISSUE THREAD

**Issue by blmoore** [EdinbR/EdinbR.github.io#1]
A sidebar might be useful to link previous posts, tags, sponsors, inline on each post. This layout change, if implemented, should maintain the responsive design (and ideally IMO keep the site looking clean and simple).

**Comment by blmoore** [comment]
Another option could be to add a list of (say) the three most recent posts to a footer below each post. This could replace the current footer image and is easy to do with jekyll.

**Comment by tbates** [comment]
Some navigation is needed: I think best fixed by adding back the home icon to the top left of the base template. That should be sufficient. 
I looked, but a lot has been changed: best if you do it?

**Comment by blmoore** [comment]
Home icon was reinstated as of 74f7a9f48a9122e4e8a5461a500611a31ec045ab — might need a hard refresh to get the new CSS
